language: csharp
solution: Expose.sln
dotnet: 5.0.100
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore Expose.sln
  - dotnet restore
  #- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - dotnet build -c Release
  - msbuild /p:Configuration=Release Expose.sln
  #- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./tests/Expose.NUnit\bin\Release\netcoreapp2.1\Expose.NUnit.dll
